import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { ThemeProvider } from "./components/providers/theme-provider";
import { cn } from "@/lib/utils";
import ToasterProvider from "@/providers/ToasterProvider";
import ModalProvider from "@/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-white dark:bg-[#121212]")}>
        <ToasterProvider />

        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          storageKey="insight"
        >
          <Sidebar>{children}</Sidebar>
        </ThemeProvider>
        <ModalProvider />
      </body>
    </html>
  );
}
